# Generated by Django 3.1.5 on 2021-01-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
