# Generated by Django 3.1.5 on 2021-01-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0002_auto_20210107_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='delegate', max_length=100),
        ),
    ]
