# Generated by Django 3.1.5 on 2021-05-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0003_auto_20210107_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=25)),
                ('grade', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
