# Generated by Django 3.1.5 on 2021-01-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('committee', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('recognized', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('committee', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('committee', models.CharField(max_length=50)),
            ],
        ),
    ]
