# Generated by Django 3.1.5 on 2021-01-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboards', '0003_auto_20210109_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsl',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rsl',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
