# Generated by Django 3.1.5 on 2021-01-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
