# Generated by Django 3.1.5 on 2021-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboards', '0006_timer_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeecontrol',
            name='allow_motions',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(),
        ),
    ]
