# Generated by Django 3.1.5 on 2021-01-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboards', '0007_auto_20210113_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
