# Generated by Django 3.1.5 on 2021-01-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboards', '0008_auto_20210113_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
