# Generated by Django 3.1.5 on 2021-05-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0010_floormods'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mods_raised', models.IntegerField(default=0)),
                ('points_raised', models.IntegerField(default=0)),
                ('placards_raised', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('added_to_sl', models.IntegerField(default=0)),
                ('award', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mods',
        ),
        migrations.AddField(
            model_name='committeecontrol',
            name='awards_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='committeecontrol',
            name='drive_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='committeecontrol',
            name='iteration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='committeecontrol',
            name='zoom_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timer',
            name='status',
            field=models.CharField(default='stop', max_length=100),
        ),
    ]
