release: python manage.py makemigrations && python manage.py migrate --run-syncdb
web: daphne lgsmun.asgi:application --port $PORT --bind 0.0.0.0 -v2
worker: python manage.py runworker channels --settings=lgsmun.settings -v2
